### ISSUE TITLE
Filtering out unwanted messages

### ISSUE THREAD

**Issue by rt121212121** [bitcoin-sv-specs/peerchannels#1]
I suspect that unless a user can avoid receiving messages they do not want, a public mailbox where they can be contacted or interacted with, is problematic. Even if the server naively imposes a cost on an anonymous user posting a message to a channel, this does not necessarily mean that that cost to the server compensates the recipient for the inconvenience of dealing with the message. Is there a plan for filtering out unwanted messages?

**Comment by Danconnolly** [comment]
This is a good point. I'm wondering whether that would belong in this spec or whether that should be an extension that is defined in another spec. I would prefer this to be in an extension.

**Comment by rt121212121** [comment]
I agree it is off-topic.
